django_movie/django_movie/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    # path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("films/", include("films.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_movie/films/urls.py
from django.urls import path

from . import views

app_name = "films"
urlpatterns = [
    path("", views.MoviesListView.as_view(), name="movies_list"),
    path("search/", views.SearchView.as_view(), name="search_list"),
    path('<uuid:pk>/', views.MovieDetailView.as_view(), name='movie_detail'),
]

django_movie/films/models.py
from django.db import models
import os

def get_img_front_upload_path(instance, filename):
    # Use the value of the img_front field as the filename
    filename = f"{instance.img_front}.jpg"
    print(filename)
    # Define the upload path within the /media/covers/ directory
    return os.path.join('covers', filename)
    
def get_img_back_upload_path(instance, filename):
    # Use the value of the img_front field as the filename
    filename = f"{instance.img_back}.jpg"
    # Define the upload path within the /media/covers/ directory
    return os.path.join('covers', filename)

class Movies(models.Model):
    id = models.CharField(primary_key=True,max_length=36, unique=True)
    movie_id = models.CharField(max_length=36, null=True)
    tv_serie_id = models.CharField(max_length=36, null=True)
    id_imdb = models.CharField(max_length=36, null=True)
    title = models.CharField(max_length=255, null=True)
    year = models.IntegerField(null=True)
    actors = models.TextField(null=True)
    genre = models.TextField(null=True)
    media_type = models.CharField(max_length=50, null=True)
    company = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)
    duration = models.IntegerField(null=True)
    type_film = models.CharField(max_length=50, null=True)
    img_front = models.CharField(max_length=36, null=True)
    img_back = models.CharField(max_length=36, null=True)
    url_img_front = models.ImageField(upload_to=get_img_front_upload_path, null=True)
    url_img_back = models.ImageField(upload_to=get_img_back_upload_path, null=True)

    def __str__(self):
        return self.title

django_movie/films/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

django_movie/films/views.py
from django.views import generic
from django.shortcuts import render
from .models import Movies
from .forms import SearchForm

app = "films"

class MoviesListView(generic.ListView):
    model = Movies
    template_name = f"{app}/index.html"
    context_object_name = 'movies'
    queryset = Movies.objects.order_by('title')[:12]
    def get_queryset(self):
        # Obtén el parámetro de la URL para determinar qué lista mostrar
        list_type = self.request.GET.get('list_type', 'top_movies')
        
        if list_type == 'full_movies':
            # Mostrar la lista completa de películas
            return Movies.objects.all().order_by('title')
        elif list_type == "dvd_movies":
            return Movies.objects.filter(type_film="DVD").order_by('title')
        elif list_type == "blue_ray_movies":
            return Movies.objects.filter(type_film="Blu-ray").order_by('title')
        else:
            # Mostrar la lista superior de películas
            return Movies.objects.order_by('title')[:12]
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_list_type'] = self.request.GET.get('list_type', 'top_movies')
        return context

class MovieDetailView(generic.DetailView):
    model = Movies
    template_name = f"{app}/movie_detail.html"
    context_object_name = 'detail'

class SearchView(generic.ListView):
    model = Movies
    template_name = f"{app}/index.html"
    context_object_name = 'all_search_results'

    def get_queryset(self):
        query = self.request.GET.get('query', '')
        result_query = Movies.objects.filter(title__icontains=query).order_by('title')
        if result_query:
            return result_query
        else:
            return Movies.objects.none()
            

django_movie/films/templates/films/index.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Peliculas</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'films/style.css' %}" type="text/css" media="all" />
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
      <ul>
        <h1 id="logo">Películas</h1>
      </ul>
    <div id="navigation">
      <ul>
        <li><a href="{% url 'films:movies_list' %}" {% if not request.GET.list_type %}class="active"{% endif %}>INICIO</a></li>
      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
		<li><a href="{% url 'films:movies_list' %}?list_type=top_movies" {% if current_list_type == 'top_movies' %}class="active"{% endif %}>TOP PELÍCULAS</a></li>
		<li><a href="{% url 'films:movies_list' %}?list_type=full_movies" {% if current_list_type == 'full_movies' %}class="active"{% endif %}>MOSTRAR TODO</a></li>
		<li><a href="{% url 'films:movies_list' %}?list_type=dvd_movies" {% if current_list_type == 'dvd_movies' %}class="active"{% endif %}>DVD</a></li>
		<li><a href="{% url 'films:movies_list' %}?list_type=blue_ray_movies" {% if current_list_type == 'blue_ray_movies' %}class="active"{% endif %}>Blue-ray</a></li>
	  </ul>
      <div id="search">
        <form method="get" accept-charset="utf-8" role="search", action = "{% url 'films:search_list' %}">
          <label for="search-field">BUSCAR</label>
          <input type="text" name="query" value="Buscar película" id="search-field" class="blink search-field"  />
          <input type="submit" value="" class="search-button" />
        </form>
      </div>
    </div>
  </div>
  <div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
        </div>
		{% for movie in all_search_results %}
			<div class="movie" id="top-movies-list">
			  <div class="movie-image"> 
				<span class="play"><span class="name">{{movie.title}}</span></span> 
				<a href="{% url 'films:movie_detail' movie.id %}">
					{% if movie.url_img_front %}
						<img src="{{ movie.url_img_front.url }}" alt="{{ movie.title }} Cover Front" />
					{% else %}
						<!-- Add a placeholder or default image if url_img_front is empty -->
						<img src="{% static 'path/to/placeholder_image.jpg' %}" alt="Placeholder Image" />
					{% endif %}
				</a> </div>
			  <div class="film-title">
				<p>{{movie.title}}</p>
				</div>
			</div>
		{% endfor %}
		{% for movie in movies %}
			<div class="movie" id="top-movies-list">
			  <div class="movie-image"> 
				<span class="play"><span class="name">{{movie.title}}</span></span> 
				<a href="{% url 'films:movie_detail' movie.id %}">
					{% if movie.url_img_front %}
						<img src="{{ movie.url_img_front.url }}" alt="{{ movie.title }} Cover Front" />
					{% else %}
						<!-- Add a placeholder or default image if url_img_front is empty -->
						<img src="{% static 'path/to/placeholder_image.jpg' %}" alt="Placeholder Image" />
					{% endif %}
				</a> </div>
			  <div class="film-title">
				<p>{{movie.title}}</p>
				</div>
			</div>
		{% endfor %}
    <div class="cl">&nbsp;</div>
      </div>
    </div>

  <div id="footer">
    <p class="lf">Copyright &copy; 2023 <a href="{% url 'films:movies_list' %}">Películas</a> - All Rights Reserved</p>
    <div style="clear:both;"></div>
  </div>
</div>
<!-- END PAGE SOURCE -->
</body>
</html>

django_movie/films/templates/films/movie_detail.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Peliculas</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'films/style.css' %}" type="text/css" media="all" />
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
      <ul>
        <h1 id="logo">Películas</h1>
      </ul>
    <div id="navigation">
      <ul>
        <li><a href="{% url 'films:movies_list' %}" {% if not request.GET.list_type %}class="active"{% endif %}>INICIO</a></li>
      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
		<li><a href="{% url 'films:movies_list' %}?list_type=top_movies" {% if current_list_type == 'top_movies' %}class="active"{% endif %}>TOP PELÍCULAS</a></li>
		<li><a href="{% url 'films:movies_list' %}?list_type=full_movies" {% if current_list_type == 'full_movies' %}class="active"{% endif %}>MOSTRAR TODO</a></li>
		<li><a href="{% url 'films:movies_list' %}?list_type=dvd_movies" {% if current_list_type == 'dvd_movies' %}class="active"{% endif %}>DVD</a></li>
		<li><a href="{% url 'films:movies_list' %}?list_type=blue_ray_movies" {% if current_list_type == 'blue_ray_movies' %}class="active"{% endif %}>Blue-ray</a></li>
	  </ul>
      <div id="search">
        <form method="get" accept-charset="utf-8" role="search", action = "{% url 'films:search_list' %}">
          <label for="search-field">BUSCAR</label>
          <input type="text" name="query" value="Buscar película" id="search-field" class="blink search-field"  />
          <input type="submit" value="" class="search-button" />
        </form>
      </div>
    </div>
  </div>
  <div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
        </div>
		<div class="detail-left">
			<div class="detail-image">
				<a>
					{% if detail.url_img_front %}
						<img src="{{ detail.url_img_front.url }}" alt="{{ detail.title }} Cover Front" />
					{% else %}
						<!-- Add a placeholder or default image if url_img_front is empty -->
						<img src="{% static 'path/to/placeholder_image.jpg' %}" alt="Placeholder Image" />
					{% endif %}
				</a> 
			</div>
		</div>
		<div class="detail-right">
		
			{% if detail.description %}
				<p id=film-description">{{detail.description}}</p>
			{% else %}
				<p id=film-description">Descripción no disponible</p>
			{% endif %}
			
			{% if detail.year %}
				<p id=film-year">Año : {{detail.year}}</p>
			{% else %}
				<p id=film-year">Año :  No disponible</p>
			{% endif %}
			
			{% if detail.genre %}
				<p id=film-year">Géneros : {{detail.genre}}</p>
			{% else %}
				<p id=film-year">Géneros :  No disponible</p>
			{% endif %}
			
			{% if detail.type_film %}
				<p id=film-year">Formato : {{detail.type_film}}</p>
			{% else %}
				<p id=film-year">Formato :  No disponible</p>
			{% endif %}
		</div>
		
		
    <div class="cl">&nbsp;</div>
      </div>
    </div>

  <div id="footer">
    <p class="lf">Copyright &copy; 2023 <a href="{% url 'films:movies_list' %}">Películas</a> - All Rights Reserved</p>
    <div style="clear:both;"></div>
  </div>
</div>
<!-- END PAGE SOURCE -->
</body>
</html>

django_movie/films/templates/films/movie_detail_v1.html
{% block content %}
    <h1>{{ detail.title }}</h1>
    <p>Year: {{ detail.year }}</p>
    <p>img_back: {{ detail.img_back }}</p>
    <p>img_front: {{ detail.img_front }}</p>
	<img src="{{ detail.url_img_front.url }}" alt="{{ detail.title }} Cover Front" />
    <!-- Add other movie details as needed -->
{% endblock %}

django_movie/films/templates/films/movie_detail_v2.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Peliculas</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{% static 'films/style_detail.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>
<body>
<div>
  <p class="logo-image"><a href="#"><img src="images/logo-image.gif" alt="" width="85" height="64" /></a></p>
  <p class="logo"><a href="#"><img src="images/logo.gif" alt="" width="315" height="32" /></a></p>
  <div class="spacer">
    <p class="menu"><a href="#">Welcome Guest</a> | <a href="#">LOG IN</a> | <a href="#">SIGN UP</a> | <a href="#">GAMES</a> | <a href="#">COMMUNITY</a> | <a href="#">SUPPORT</a> | <a href="#">STORES</a></p>
  </div>
</div>
<div class="left-div-wrapper">
  <p><img src="images/banner.jpg" alt="" width="353" height="538" /></p>
  <p><img src="images/our-tech-partners.gif" alt="" width="177" height="17" /><img src="images/ubi-logo.jpg" alt="" width="86" height="67" class="ubi-logo" /></p>
  <div class="spacer">&nbsp;</div>
</div>
<div class="right-div-wrapper">
  <p class="heading"><img src="images/new-games-arrivel.gif" alt="" width="298" height="19" /></p>
  <p> This is Gamezone, a free, fully standards-compliant CSS template designed by Free CSS Templates.<br />
    This free template is released under a Creative Commons Attributions 2.5 license, so you're pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :) </p>
  <p class="divider-body">&nbsp;</p>
  <p class="game-image"><a href="#" class="pic"><img src="images/game-01.jpg" alt="" width="120" height="90" /></a><br />
    <a href="#">Demo Game 1</a></p>
  <p class="game-image"><a href="#" class="pic"><img src="images/game-02.jpg" alt="" width="120" height="90" /></a><br />
    <a href="#">Demo Game 2</a></p>
  <p class="game-image"><a href="#" class="pic"><img src="images/game-03.jpg" alt="" width="120" height="90" /></a><br />
    <a href="#">Demo Game 3</a></p>
  <div class="spacer">&nbsp;</div>
  <p class="divider-body">&nbsp;</p>
  <p class="heading"><img src="images/game-index.gif" alt="" width="101" height="19" /></p>
  <ul>
    <li><a href="#">Nunc eu massa</a></li>
    <li><a href="#">nec quam vulputate</a></li>
    <li><a href="#">vulputate</a></li>
    <li><a href="#">Morbi malesuada mollis</a></li>
    <li><a href="#">Fusce tempus diam ac</a></li>
    <li><a href="#">neque. Nam tempor.</a></li>
  </ul>
  <ul>
    <li><a href="#">Nunc eu massa</a></li>
    <li><a href="#">nec quam vulputate</a></li>
    <li><a href="#">vulputate</a></li>
    <li><a href="#">Morbi malesuada mollis</a></li>
    <li><a href="#">Fusce tempus diam ac</a></li>
    <li><a href="#">neque. Nam tempor.</a></li>
  </ul>
  <p class="game-image"><a href="#" class="pic"><img src="images/game-04.jpg" alt="" width="120" height="90" /></a><br />
    <a href="#">Demo Game 4 </a></p>
  <p class="game-image"><a href="#" class="pic"><img src="images/game-05.jpg" alt="" width="120" height="90" /></a><br />
    <a href="#">Demo Game 5 </a></p>
  <p class="game-image"><a href="#" class="pic"><img src="images/game-06.jpg" alt="" width="120" height="90" /></a><br />
    <a href="#">Demo Game 6 </a></p>
  <div class="spacer">&nbsp;</div>
  <p class="divider-body">&nbsp;</p>
  <p class="footer">Copyright @ 2023, <a href="#">Peliculas</a>, all rights reserved.</p>
</div>
</body>
</html>